---
# copyright Utrecht University

- name: Ensure Redis is installed
  package:
    name: redis
    state: present
  tags: role_redis


- name: Ensure Redis is configured
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    mode: 0644
  notify: Restart Redis
  tags: role_redis

- name: Set Linux kernel setting to improve Redis performance
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
  notify: Restart Redis
  tags: role_redis

- name: Allow Redis to listen on port 6379
  seport:
    ports: 6379
    proto: tcp
    setype: redis_port_t
    state: present
  notify: Restart Redis
  tags: role_redis

- name: Ensure Redis is running and enabled on boot
  service:
    name: redis
    state: started
    enabled: yes
  tags: role_redis
