---
# copyright Utrecht University

- name: Ensure Apache webserver is installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
  - httpd
  - mod_ssl
  - openssl



- name: Ensure customized httpd config is present
  template:
    src: 'httpd.conf.j2'
    dest: '/etc/httpd/conf/httpd.conf'
    mode: 0600
  notify: Restart Apache webserver



- name: Ensure customized SSL config is present
  template:
    src: 'ssl.conf.j2'
    dest: '/etc/httpd/conf.d/ssl.conf'
    mode: 0600
  notify: Restart Apache webserver



- name: Ensure autoindex.conf is absent
  file:
    path: '{{ item }}'
    state: absent
  notify: Restart Apache webserver
  with_items:
  - /etc/httpd/conf.d/autoindex.conf


- name: Allow execution of files in /temp
  become: yes
  shell: /usr/sbin/setsebool httpd_tmp_exec on

