---
# This playbook deploys a complete CKAN instance.

- hosts: solr
  connection: local
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: 
  become: yes
  roles:
    - common
    - certificates
    - apache
    - solr

- name: Provision CKAN server
  hosts: ckan
  connection: local
  become: true
  gather_facts: true
  vars:
    solr_url: 
    database_username:
    database_password:                                 # CKAN Postgresql database password
    database_url: 
    ckan_admin_password: test                                      # CKAN admin user ('ckanadmin') password
    ckan_harvest_password: test                                    # CKAN harvest user ('harvest') password
    epos_msl_version: development
    epos_msl_fqdn:  gris.syngentaaws.org                           # fully qualified domain name (FQDN)
    epos_msl_environment: development                              # environment: development, testing, acceptance or production
    ckan_branch: ckan-2.7.3 
    ckanext_oauth2_branch: master 
    ckanext_scheming_branch: master 
    ckanext_spatial_branch: master
    syngenta_theme_branch: Dev
    ckan_harvest_branch: 65e3163015079f425805a6b35458b1b1bf6d0ce0 
  roles:
    - { role: common,          tags: ['role_common'] }
    - { role: certificates,    tags: ['role_certificates'] }
    - { role: apache,          tags: ['role_apache'] }
    - { role: postgresql,      tags: ['role_postgresql'] }
    - { role: solr,            tags: ['role_solr'] }
    - { role: redis,           tags: ['role_redis'] }
    - { role: ckan,            tags: ['ckan']  }
    - { role: ckan-harvester,  tags: ['role_ckan_harvester'] }
