
- name: Ensure dependencies for Ansible OpenSSL module are installed
  package:
    name: pyOpenSSL
    state: present
  tags: role_certificates


- name: Ensure OpenSSL 4096 bits RSA private key is present
  openssl_privatekey:
    path: '{{ openssl_private_dir }}/{{ openssl_key_selfsigned }}'
    size: 4096
    type: RSA
    force: False
    state: present
  tags: role_certificates


- name: Ensure OpenSSL certificate signing request is present
  command: "openssl req -new -sha256 \
    -key '{{ openssl_private_dir }}/{{ openssl_key_selfsigned }}' \
    -out '{{ openssl_csr_selfsigned }}' -batch -subj \
    '/O={{ openssl_o }}/C={{ openssl_c }}\
     /localityName={{ openssl_localityName }}\
     /commonName={{ openssl_cn }}'"
  args:
    chdir: '{{ openssl_certs_dir }}'
    creates: '{{ openssl_csr_selfsigned }}'
  tags: role_certificates


- name: Ensure OpenSSL self signed certificate is present
  command: >
    openssl x509 -req -days 365
    -in '{{ openssl_csr_selfsigned }}'
    -signkey '{{ openssl_private_dir }}/{{ openssl_key_selfsigned }}'
    -out '{{ openssl_crt_selfsigned }}'
  args:
    chdir: '{{ openssl_certs_dir }}'
    creates: '{{ openssl_crt_selfsigned }}'
  tags: role_certificates


- name: Ensure OpenSSL signed private key is present
  command: >
    cp '{{ openssl_private_dir }}/{{ openssl_key_selfsigned }}'
    '{{ openssl_private_dir }}/{{ openssl_key_signed }}'
  args:
    creates: '{{ openssl_private_dir }}/{{ openssl_key_signed }}'
  tags: role_certificates


- name: Ensure OpenSSL signed certificate is present
  command: >
    cp '{{ openssl_certs_dir }}/{{ openssl_crt_selfsigned }}'
    '{{ openssl_certs_dir }}/{{ openssl_crt_signed }}'
  args:
    creates: '{{ openssl_certs_dir }}/{{ openssl_crt_signed }}'
  tags: role_certificates


- name: Ensure Diffie-Hellman parameters are generated
  command: openssl dhparam -2 -out {{ openssl_dhparams }} 2048
  args:
    chdir: '{{ openssl_private_dir }}'
    creates: '{{ openssl_private_dir }}/{{ openssl_dhparams }}'
  tags: role_certificates

